import React from "react";
import { Link } from "react-router-dom";

export default function Home() {
  return (
    <div className="min-vh-100 bg-gradient-primary">
      {/* Hero Section */}
      <div className="container-fluid bg-primary text-white py-4 py-lg-5">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6 mb-4 mb-lg-0">
              <h1 className="display-4 fw-bold mb-3 mb-lg-4">
                AI-Powered Quiz Social Network
              </h1>
              <p className="lead mb-3 mb-lg-4">
                Create, share, and discover intelligent quizzes generated by AI. 
                Connect with friends, challenge your knowledge, and build a community 
                around learning and fun.
              </p>
              <div className="d-flex gap-2 gap-lg-3 flex-wrap">
                <Link to="/register" className="btn btn-light btn-lg px-3 px-lg-4 flex-fill flex-lg-fill-0">
                  Get Started Free
                </Link>
                <Link to="/login" className="btn btn-outline-light btn-lg px-3 px-lg-4 flex-fill flex-lg-fill-0">
                  Sign In
                </Link>
              </div>
            </div>

            <div className="col-lg-6 text-center">
              <div className="bg-white bg-opacity-10 rounded-3 p-3 p-lg-4">
                <i className="bi bi-robot display-1 text-light"></i>
                <h3 className="mt-3 h4 h3-lg">AI-Generated Content</h3>
                <p className="mb-0">Smart quizzes tailored to your interests</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="container py-4 py-lg-5">
        <div className="row text-center mb-4 mb-lg-5">
          <div className="col-12">
            <h2 className="display-5 fw-bold mb-3">Why Choose Our Platform?</h2>
            <p className="lead text-muted">
              Experience the future of social learning with AI-powered features
            </p>
          </div>
        </div>
        
        <div className="row g-3 g-lg-4 mb-4 mb-lg-5">
          <div className="col-12 col-md-6 col-lg-4">
            <div className="card h-100 border-0 shadow-sm">
              <div className="card-body text-center p-3 p-lg-4">
                <div className="bg-primary bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '60px', height: '60px'}}>
                  <i className="bi bi-magic text-primary" style={{fontSize: '1.5rem'}}></i>
                </div>
                <h4 className="card-title h5">AI Quiz Generation</h4>
                <p className="card-text text-muted small">
                  Create engaging quizzes instantly with our advanced AI that adapts 
                  to your content and generates relevant questions.
                </p>
              </div>
            </div>
          </div>
          
          <div className="col-12 col-md-6 col-lg-4">
            <div className="card h-100 border-0 shadow-sm">
              <div className="card-body text-center p-3 p-lg-4">
                <div className="bg-success bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '60px', height: '60px'}}>
                  <i className="bi bi-people text-success" style={{fontSize: '1.5rem'}}></i>
                </div>
                <h4 className="card-title h5">Social Learning</h4>
                <p className="card-text text-muted small">
                  Connect with friends, share your quizzes, and challenge others. 
                  Build a community around knowledge and friendly competition.
                </p>
              </div>
            </div>
          </div>
          
          <div className="col-12 col-md-6 col-lg-4">
            <div className="card h-100 border-0 shadow-sm">
              <div className="card-body text-center p-3 p-lg-4">
                <div className="bg-info bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '60px', height: '60px'}}>
                  <i className="bi bi-graph-up text-info" style={{fontSize: '1.5rem'}}></i>
                </div>
                <h4 className="card-title h5">Progress Tracking</h4>
                <p className="card-text text-muted small">
                  Monitor your learning progress, track quiz performance, and 
                  discover areas for improvement with detailed analytics.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* How It Works Section */}
      <div className="container-fluid bg-light py-4 py-lg-5">
        <div className="container">
          <div className="row text-center mb-4 mb-lg-5">
            <div className="col-12">
              <h2 className="display-5 fw-bold mb-3">How It Works</h2>
              <p className="lead text-muted">Get started in just three simple steps</p>
            </div>
          </div>
          
          <div className="row g-3 g-lg-4">
            <div className="col-12 col-md-4 text-center">
              <div className="position-relative">
                <div className="bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '50px', height: '50px'}}>
                  <span className="fw-bold">1</span>
                </div>
                <h5 className="h6">Create Your Account</h5>
                <p className="text-muted small">Sign up for free and join our community of learners and creators.</p>
              </div>
            </div>
            
            <div className="col-12 col-md-4 text-center">
              <div className="position-relative">
                <div className="bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '50px', height: '50px'}}>
                  <span className="fw-bold">2</span>
                </div>
                <h5 className="h6">Generate AI Quizzes</h5>
                <p className="text-muted small">Use our AI to create engaging quizzes or play existing ones from the community.</p>
              </div>
            </div>
            
            <div className="col-12 col-md-4 text-center">
              <div className="position-relative">
                <div className="bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '50px', height: '50px'}}>
                  <span className="fw-bold">3</span>
                </div>
                <h5 className="h6">Connect & Share</h5>
                <p className="text-muted small">Share your quizzes, challenge friends, and grow your network.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="container py-4 py-lg-5">
        <div className="row justify-content-center">
          <div className="col-lg-8 text-center">
            <h2 className="display-5 fw-bold mb-3 mb-lg-4">Ready to Start Learning?</h2>
            <p className="lead text-muted mb-3 mb-lg-4">
              Join thousands of users who are already creating, sharing, and learning 
              with AI-powered quizzes.
            </p>
            <div className="d-flex gap-2 gap-lg-3 justify-content-center flex-wrap">
              <Link to="/register" className="btn btn-primary btn-lg px-4 px-lg-5 flex-fill flex-lg-fill-0">
                Create Free Account
              </Link>
              <Link to="/quiz-list" className="btn btn-outline-primary btn-lg px-4 px-lg-5 flex-fill flex-lg-fill-0">
                Browse Quizzes
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-dark text-white py-4 mt-5">
        <div className="container text-center">
          <p className="mb-0">
            © 2024 AI Quiz Social Network. Built with React and powered by AI.
          </p>
        </div>
      </footer>
    </div>
  );
}
