import React from "react";
import { Link } from "react-router-dom";

export default function Home() {
  return (
    <div className="min-vh-100 bg-gradient-primary">
      {/* Hero Section */}
      <div className="container-fluid bg-primary text-white py-5">
        <div className="container">
          <div className="row align-items-center">
            <div className="col-lg-6">
              <h1 className="display-4 fw-bold mb-4">
                AI-Powered Quiz Social Network
              </h1>
              <p className="lead mb-4">
                Create, share, and discover intelligent quizzes generated by AI. 
                Connect with friends, challenge your knowledge, and build a community 
                around learning and fun.
              </p>
              <div className="d-flex gap-3 flex-wrap">
                  <Link to="/register" className="btn btn-light btn-lg px-4">
                    Get Started Free
                  </Link>
                  <Link to="/login" className="btn btn-outline-light btn-lg px-4">
                    Sign In
                  </Link>
                </div>
              </div>

              <div className="col-lg-6 text-center">
                <div className="bg-white bg-opacity-10 rounded-3 p-4">
                  <i className="bi bi-robot display-1 text-light"></i>
                  <h3 className="mt-3">AI-Generated Content</h3>
                  <p className="mb-0">Smart quizzes tailored to your interests</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="container py-5">
        <div className="row text-center mb-5">
          <div className="col-12">
            <h2 className="display-5 fw-bold mb-3">Why Choose Our Platform?</h2>
            <p className="lead text-muted">
              Experience the future of social learning with AI-powered features
            </p>
          </div>
        </div>
        
        <div className="row g-4 mb-5">
          <div className="col-md-4">
            <div className="card h-100 border-0 shadow-sm">
              <div className="card-body text-center p-4">
                <div className="bg-primary bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '80px', height: '80px'}}>
                  <i className="bi bi-magic text-primary" style={{fontSize: '2rem'}}></i>
                </div>
                <h4 className="card-title">AI Quiz Generation</h4>
                <p className="card-text text-muted">
                  Create engaging quizzes instantly with our advanced AI that adapts 
                  to your content and generates relevant questions.
                </p>
              </div>
            </div>
          </div>
          
          <div className="col-md-4">
            <div className="card h-100 border-0 shadow-sm">
              <div className="card-body text-center p-4">
                <div className="bg-success bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '80px', height: '80px'}}>
                  <i className="bi bi-people text-success" style={{fontSize: '2rem'}}></i>
                </div>
                <h4 className="card-title">Social Learning</h4>
                <p className="card-text text-muted">
                  Connect with friends, share your quizzes, and challenge others. 
                  Build a community around knowledge and friendly competition.
                </p>
              </div>
            </div>
          </div>
          
          <div className="col-md-4">
            <div className="card h-100 border-0 shadow-sm">
              <div className="card-body text-center p-4">
                <div className="bg-info bg-opacity-10 rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '80px', height: '80px'}}>
                  <i className="bi bi-graph-up text-info" style={{fontSize: '2rem'}}></i>
                </div>
                <h4 className="card-title">Progress Tracking</h4>
                <p className="card-text text-muted">
                  Monitor your learning progress, track quiz performance, and 
                  discover areas for improvement with detailed analytics.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* How It Works Section */}
      <div className="container-fluid bg-light py-5">
        <div className="container">
          <div className="row text-center mb-5">
            <div className="col-12">
              <h2 className="display-5 fw-bold mb-3">How It Works</h2>
              <p className="lead text-muted">Get started in just three simple steps</p>
            </div>
          </div>
          
          <div className="row g-4">
            <div className="col-md-4 text-center">
              <div className="position-relative">
                <div className="bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '60px', height: '60px'}}>
                  <span className="fw-bold">1</span>
                </div>
                <h5>Create Your Account</h5>
                <p className="text-muted">Sign up for free and join our community of learners and creators.</p>
              </div>
            </div>
            
            <div className="col-md-4 text-center">
              <div className="position-relative">
                <div className="bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '60px', height: '60px'}}>
                  <span className="fw-bold">2</span>
                </div>
                <h5>Generate AI Quizzes</h5>
                <p className="text-muted">Use our AI to create engaging quizzes or play existing ones from the community.</p>
              </div>
            </div>
            
            <div className="col-md-4 text-center">
              <div className="position-relative">
                <div className="bg-primary text-white rounded-circle d-inline-flex align-items-center justify-content-center mb-3" style={{width: '60px', height: '60px'}}>
                  <span className="fw-bold">3</span>
                </div>
                <h5>Connect & Share</h5>
                <p className="text-muted">Share your quizzes, challenge friends, and grow your network.</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="container py-5">
        <div className="row justify-content-center">
          <div className="col-lg-8 text-center">
            <h2 className="display-5 fw-bold mb-4">Ready to Start Learning?</h2>
            <p className="lead text-muted mb-4">
              Join thousands of users who are already creating, sharing, and learning 
              with AI-powered quizzes.
            </p>
            <div className="d-flex gap-3 justify-content-center flex-wrap">
              <Link to="/register" className="btn btn-primary btn-lg px-5">
                Create Free Account
              </Link>
              <Link to="/quiz-list" className="btn btn-outline-primary btn-lg px-5">
                Browse Quizzes
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-dark text-white py-4 mt-5">
        <div className="container text-center">
          <p className="mb-0">
            © 2024 AI Quiz Social Network. Built with React and powered by AI.
          </p>
        </div>
      </footer>
    </div>
  );
}
